# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c1737f0ee8d7e4553f6c13a4c758bf6b6d8359ff0c5ce6aedc32b804c73b89961b10c95fbd1d1cf278d699370750e3bf24a03e4689ab9301d30c1ca56d23a76

test:
  secret_key_base: af9ccf31d1d5b4c9a4ac526c7592334ee7eb873da8ebe0895f7a58712b36ea487b73aae1739b9d134db1a4867ec0c1c567fcf5f7500344e2586f170d7867d9c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
